version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.20
    container_name: es7
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - esnet

networks:
  esnet:
